name: Deploy and Capture Screenshot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Site
      run: echo "Building site..."

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './'
        cname: '<username>.github.io'  # Optional if using a custom domain

    - name: Capture Screenshot
      run: npm run screenshot

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: result-screenshot
        path: result.png
